name: clone_ig
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  # firebase_auth: ^0.16.0
  # google_sign_in: ^4.5.1
  # url_launcher: ^5.4.10
  # firebase_messaging: ^6.0.15
  http: ^0.12.1
  intl: ^0.16.1
  image_picker: ^0.6.6+4
  # shared_preferences: ^0.5.7+3
  # webview_flutter: ^0.3.22+1
  cached_network_image: ^2.2.0+1
  firebase_core: ^0.4.4+3
  connectivity: ^0.4.8+6
  # firebase_remote_config: ^0.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
